baseURL = 'https://data-analysis-curriculum.netlify.app/'
languageCode = 'en-us'
title = 'Data Analysis Curriculum'

theme = "hugo-theme-relearn"
ignoreLogs = ['warning-goldmark-raw-html']

canonifyUrls = true

[outputs]
  home = ["HTML", "RSS"]

[params]
  themeVariant = ["lc-light", "lc-dark-blue", "lc-dark-blue-two"]
